# Generated by Django 3.1.2 on 2020-10-27 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_orders_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='price',
            new_name='total_price',
        ),
    ]
